### PR TITLE
Update docker-rules.mk

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by moul** [comment]
Depends on https://github.com/scaleway/scaleway-cli/pull/176 but it works :)

**Comment by moul** [comment]
```console
$ scw inspect $(VOLUME_SIZE=150G IMAGE_NAME=coucou IMAGE_BOOTSCRIPT=docker sh -x create-image-from-s3.sh http://store.scw.42.am/scw/scw-distrib-debian-jessie.tar)
```
```json
[{
  "id": "00000000-0000-1000-0000-000000000000",
  "name": "coucou",
  "creation_date": "2015-09-10T08:58:57.317907+00:00",
  "modification_date": "2015-09-10T08:58:57.317907+00:00",
  "root_volume": {
    "id": "11111111-1111-1111-1111-111111111111",
    "size": 150000000000,
    "name": "scw-distrib-debian-jessie-2015-09-10_10:54",
    "volume_type": "l_ssd"
  },
  "default_bootscript": {
    "id": "22222222-2222-1222-2222-222222222222",
    "title": "4.1.6-docker #250",
    "bootcmdargs": {
      "id": "33333333-3333-1333-3333-333333333333",
      "value": "LINUX_COMMON ip=dhcp boot=local root=/dev/nbd0 nbd.max_parts=8"
    },
    "initrd": {
      "id": "44444444-4444-1444-4444-444444444444",
      "path": "initrd/c1-uInitrd-v3.3",
      "title": "C1 uInitrd v3.3"
    },
    "kernel": {
      "id": "55555555-5555-1555-5555-555555555555",
      "dtb": "dtb/pimouss-computing.dtb.4.1.6-250-docker",
      "path": "kernel/pimouss-uImage-4.1.6-250-docker",
      "title": "Pimouss 4.1.6-250-docker"
    }
  },
  "organization": "66666666-6666-1666-6666-666666666666",
  "arch": "arm"
}]
```

**Comment by aimxhaisse** [comment]
lgtm

**Comment by QuentinPerez** [comment]
LGTM

**Pull request merged**
